[FEATURES TO IMPLEMENT]
 To do:
 - Add `Szmelc Commander` main dir path
 - Add 'Usr & Group'
 - Add Repositories as .txt, .yml or .sh file and path to select
(Allow multiple repositories, prompt user which repo to szmelc on startup)
 - Add dependency management
 - Add ...
